import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from "next/link";
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/agoda.svg"
            alt="Agoda Logo"
            width={800}
            height={240}
            priority
          />
        </div>

        <div className={styles.grid}>
          <Link
            href="/about"
            className={styles.card}
          >
            <h2 className={inter.className}>
              About (Link) <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Assignment 2 - Create about.tsx and route to the page
            </p>
          </Link>

          <Link
              href="/about"
            className={styles.card}
          >
            <h2 className={inter.className}>
              About (Anchor) <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Compare client-side navigation with browser navigation (Anchor)
            </p>
          </Link>

          <Link
              href="/static"
              className={styles.card}
          >
            <h2 className={inter.className}>
              Static Props Example<span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              This gets called on build time
            </p>
          </Link>

          <Link
              href="/server"
              className={styles.card}
          >
            <h2 className={inter.className}>
              ServerSide Props Example<span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              This gets called on every request
            </p>
          </Link>

          <Link
              href="/persons"
              className={styles.card}
          >
            <h2 className={inter.className}>
              Static Props Example<span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Another example of static props
            </p>
          </Link>

        </div>
      </main>
    </>
  )
}
